### ISSUE TITLE
'logged' documentation is 'post' request

### ISSUE THREAD

**Issue by Nirmitjatana** [GDGVIT/AttendanceApp-Backend#16]
it should be 'Get' @D-E-F-E-A-T

**Comment by D-E-F-E-A-T** [comment]
:+1:

**Comment by D-E-F-E-A-T** [comment]
Heading: *logged* route has method *post*.
Comment: It should be *GET* as it's only needs JWT in  header
@Nirmitjatana

**Comment by D-E-F-E-A-T** [comment]
[Resolved](https://github.com/GDGVIT/AttendanceApp-Backend/pull/14/commits/c61f7c50d2bd430d4ce099ee88a3315beb596e4c)

**Comment by D-E-F-E-A-T** [comment]
@Nirmitjatana You can close this issue now.
