### ISSUE TITLE
Add admin="true/false" route to login 

### ISSUE THREAD

**Issue by Nirmitjatana** [GDGVIT/AttendanceApp-Backend#18]

**Comment by D-E-F-E-A-T** [comment]
[Resolved](https://github.com/D-E-F-E-A-T/AttendanceApp-Backend/commit/4e52f7fad3169cd418aae78d7b8f25e148ccca5b) @Nirmitjatana

**Comment by D-E-F-E-A-T** [comment]
@Nirmitjatana you can close it.
