### ISSUE TITLE
route for attendance update should be attendence/update

### ISSUE THREAD

**Issue by Nirmitjatana** [GDGVIT/AttendanceApp-Backend#19]
right now the route is:
attendence/update/mail@mail

**Comment by Nirmitjatana** [comment]
@D-E-F-E-A-T

**Comment by D-E-F-E-A-T** [comment]
I have created a new route as you asked for.
Both have their advantage, u can use any of them now.
Close the issue after testing it works @Nirmitjatana

**Comment by D-E-F-E-A-T** [comment]
@Nirmitjatana

**Comment by oct111998** [comment]
@Nirmitjatana Close the issue it's been solved from so long.

**Comment by oct111998** [comment]
@Geek-ubaid issue is resolved but kept open. Can u ask to get it closed, I don't like issues.

**Comment by Geek-ubaid** [comment]
The person who has created the issue should close it.  Okay I am closing the issue.
