### ISSUE TITLE
Code Factoring

### ISSUE THREAD

**Issue by D-E-F-E-A-T** [GDGVIT/AttendanceApp-Backend#2]
Bring Modularity

**Comment by L04DB4L4NC3R** [comment]
> Bring Modularity

This is top priority once #1 is merged

**Comment by D-E-F-E-A-T** [comment]
@L04DB4L4NC3R ok :rofl:

**Comment by D-E-F-E-A-T** [comment]
[Resolved](https://github.com/GDGVIT/AttendanceApp-Backend/pull/7#issue-369942110)
