### ISSUE TITLE
finish unitesting

### ISSUE THREAD

**Issue by D-E-F-E-A-T** [GDGVIT/AttendanceApp-Backend#9]
![image](https://user-images.githubusercontent.com/41824020/73660323-f74cf300-46bd-11ea-80d7-b0ddd4eae877.png)

**Comment by Geek-ubaid** [comment]
Is this issue resolved?

**Comment by D-E-F-E-A-T** [comment]
@Geek-ubaid No.
I close any issue as soon as It's Resolved.
Reolved Commit can be found attached with the issue.

**Comment by D-E-F-E-A-T** [comment]
https://github.com/GDGVIT/AttendanceApp-Backend/pull/14/commits/1a869fb2875885a5cfec9a75dc0f22e1260aa0d3
